---
name: bomber
version: 17.08.1
summary: Arcade Bombing Game
description: |-
    Bomber is a single player arcade game. The player is invading various cities in a plane that is decreasing in height.

    The goal of the game is to destroy all the buildings and advance to the next level. Each level gets a bit harder by increasing the speed of the plane and the height of the buildings.
confinement: strict
grade: stable
apps:
    bomber:
        command: kf5-launch bomber
        plugs:
        - kde-frameworks-5-plug
        - home
        - x11
        - opengl
        - network
        - network-bind
        - unity7
        - pulseaudio
slots:
    session-dbus-interface:
        interface: dbus
        name: org.kde.bomber
        bus: session
plugs:
    kde-frameworks-5-plug:
        content: kde-frameworks-5-all
        interface: content
        default-provider: kde-frameworks-5
        target: kf5
parts:
    bomber:
        after:
        - kde-frameworks-5-dev
        - kde-frameworks-5-env
        plugin: cmake
        build-packages:
        - kdoctools-dev
        - libkf5kdegames-dev
        - libkf5kdelibs4support-dev
        - libphonon4qt5-dev
        - libphonon4qt5experimental-dev
        - libpulse0
        source: https://download.kde.org/stable/applications/17.08.1/src/bomber-17.08.1.tar.xz
        configflags:
        - "-DKDE_INSTALL_USE_QT_SYS_PATHS=ON"
        - "-DCMAKE_INSTALL_PREFIX=/usr"
        - "-DCMAKE_BUILD_TYPE=Release"
        - "-DENABLE_TESTING=OFF"
        - "-DBUILD_TESTING=OFF"
        - "-DKDE_SKIP_TEST_SETTINGS=ON"
